title: Wan Shafiqah
logo: https://github.com/shanurwan/portfolio1/blob/main/profilepic/cropped_circle_image.png
description: I make data work harder so people don't have to
theme: jekyll-theme-modernist
