title: Wan Nur Shafiqah
logo: https://raw.githubusercontent.com/shanurwan/portfolio1/main/profilepic/cropped_circle_image.png
description: I make data work harder so people don't have to
theme: jekyll-theme-cayman
